name: Build
on: push
jobs:
  build:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: macos-latest
    env:
      TYPST_VERSION: 0.14.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          brew update
          brew install binaryen

      - name: Install Typst
        run: |
          mkdir "$HOME/.local/bin"
          curl -L https://github.com/typst/typst/releases/download/v$TYPST_VERSION/typst-aarch64-apple-darwin.tar.xz | bsdtar xJf - --strip-components=1 -C "$HOME/.local/bin" */typst
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build -p "$HOME/Library/Application Support/typst" -Doptimize=${{ matrix.optimize }}

      - name: Test
        run: |
          cd pkg/examples
          typst compile demo.typ

      - name: Pack
        run: zig build pack -Doptimize=${{ matrix.optimize }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: neoplot-${{ matrix.optimize }}
          path: zig-out/neoplot-*.tar.xz
          if-no-files-found: error
