name: Test
on: push
jobs:
  test:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: macos-latest
    env:
      TYPST_VERSION: 0.14.0-rc.1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install binaryen

      - name: Install Typst
        run: |
          mkdir "$HOME/.local/bin"
          curl -L https://github.com/typst/typst/releases/download/v$TYPST_VERSION/typst-aarch64-apple-darwin.tar.xz | bsdtar xJf - --strip-components=1 -C "$HOME/.local/bin" */typst
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build -Doptimize=${{ matrix.optimize }}

      - name: Test
        run: |
          cd pkg
          typst compile --root . examples/demo.typ
